name: user_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  persistent_bottom_nav_bar:
  flutter_map:
  characters:
  provider: ^3.0.0+1
  toggle_switch:
  http:
  image_picker:

flutter:

  uses-material-design: true
  assets:

    - assets/uu.jpg
